<!--Because php wasn't permitted in this file, I have used html to style this web page to look like the rest. -->
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book events</title>
    <link href="style.css" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
</head>
<body>
<div id="gridContainer">
    <header>
        <h1>northEvents - Book Events</h1>
    </header>
    <nav>
        <h2>Links</h2>
        <ul>
            <li><a href='index.php'>Home</a></li>
            <li><a href='bookEventsForm.php'>Book Events</a></li>
            <li><a href='admin.php'>Admin</a></li>
            <li><a href='credits.php'>Credits</a></li>
        </ul>
    </nav>
    <form class="login" method="post" action="loginProcess.php">
        <label>
            Username <input type="text" name="username">
        </label>
        <label>
            Password <input type="password" name="password">
        </label>
        <input class="loginButton" type="submit" value="login">
    </form>
    <main id="bookEventsMain">
        <h3>Book Events</h3>
        <?php
        /* This code dynamically generates a web page containing a form designed with the html required to display one
        checkbox for each of the records currently held in the nmc_records database table has been provided for you in the
        assessment section for the module on blackboard. The user can select one or more records that they are interested in
        ordering by clicking the checkboxes.
        Use the browser to look at the structure of the html generated by the php code. */

        $url = "http://unn-izge1.newnumyspace.co.uk/KF5002/assessment/bookEventsForm.php";
        $curl = curl_init($url);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        $result = curl_exec($curl);
        curl_close($curl);
        echo $result;
        ?>
    </main>
    <script type="text/javascript" src="functions.js"></script>
    <footer>
        <p>created by Grant A w18013678</p>
    </footer>
</div>
</body>
</html>